# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  type: ClusterIP
  ports:
  - name: jellyfin
    protocol: TCP
    port: 8096
    targetPort: 8096
---
