open-webui:
  ollama:
    enabled: true
    models:
      - llama3.1
      - mistral
    requests:
      cpu: "2000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "4Gi"

  clusterDomain: cluster.local
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
