{{- if .Values.configAsCode.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "adguard-home.name" . }}
    helm.sh/chart: {{ include "adguard-home.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  AdGuardHome.yaml: |
    {{- toYaml .Values.configAsCode.config | nindent 4 }}
{{- end }}
