apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - "adguard"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adguard-adguard-home
            port:
              number: 3000
