apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'gitea@localhost:nambrosini/homelab.git'
    path: applications
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
