apiVersion: v2
name: homepage
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: homepage
    repository: https://jameswynn.github.io/helm-chart
    version: 2.0.1

