# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  selector:
    app: sonarr
  type: ClusterIP
  ports:
  - name: sonarr
    protocol: TCP
    port: 8989
    targetPort: 8989
---

