apiVersion: v2
name: tailscale
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: tailscale-operator
    repository: https://pkgs.tailscale.com/helmcharts
    version: 1.70.0
