---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  radarr
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        envFrom:
        - configMapRef:
            name: radarr-cm
        ports:
        - containerPort: 7878
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 7878
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 2
          httpGet:
            port: 7878
          timeoutSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /config
        - name: movies
          mountPath: /movies
        - name: import
          mountPath: /import
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: radarr-data
      - name: movies
        hostPath:
          path: "/media/library/movies"
          type: "Directory"
      - name: import
        hostPath:
          path: "/media/library/import/movies"
          type: "Directory"
      - name: downloads
        hostPath:
          path: "/media/library/downloads"
          type: "Directory"
      restartPolicy: Always

