# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    app: radarr
  type: ClusterIP
  ports:
  - name: radarr
    protocol: TCP
    port: 7878
    targetPort: 7878
---

