apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actualbudget
  namespace: argocd
spec:
  destination:
    namespace: actualbudget
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/actualbudget
    repoURL: 'https://github.com/nambrosini/homelab'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
