apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
spec:
  destination:
    namespace: firefly
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/firefly
    repoURL: 'https://github.com/nambrosini/homelab'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
