apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    namespace: homepage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/homepage
    repoURL: 'https://github.com/nambrosini/homelab'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
