# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
  labels:
    app: actualbudget
spec:
  selector:
    matchLabels:
      app: actualbudget
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  actualbudget
      labels:
        app: actualbudget
    spec:
      containers:
      - name: actualbudget
        image: actualbudget/actual-server:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 5006
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 5006
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 5006
          name: actualbudget
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actualbudget-pvc
      restartPolicy: Always
---

