apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actualbudget-ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - "actualbudget"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: actualbudget
            port:
              number: 5006
---
