# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: actualbudget
spec:
  selector:
    app: actualbudget
  type: ClusterIP
  ports:
  - name: actualbudget
    protocol: TCP
    port: 5006
    targetPort: 5006
---

