pihole:
  DNS1:
    208.67.222.222
  DNS2: 
    208.67.220.220
  persistentVolumeClaim:
    enabled: true
    storageClass: "longhorn"
  replicaCount: 1
  serviceDns:
    type: LoadBalancer
    annotations:
      tailscale.com/expose: "true"
