service:
  dns-tcp:
    annotations:
      tailscale.com/expose: "true"
  dns-udp:
    annotations:
      tailscale.com/expose: "true"
persistence:
  config:
    enabled: true
    storageClass: "longhorn"
  data:
    enabled: true
    storageClass: "longhorn"
