apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - "ollama"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 80
---
