# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  selector:
    app: prowlarr
  type: ClusterIP
  ports:
  - name: prowlarr
    protocol: TCP
    port: 9696
    targetPort: 9696
---

