# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-config
data:
  APP_KEY: 4EWC2G4WMvHjXyzJBN4yhohjqQDxEcIT
  DB_HOST: postgres.postgres.svc.cluster.local
  DB_PORT: "5432"
  DB_CONNECTION: pgsql
  DB_DATABASE: firefly
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
---

