# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: freshrss
spec:
  selector:
    app: freshrss
  type: ClusterIP
  ports:
  - name: freshrss
    protocol: TCP
    port: 80
    targetPort: 80
---

