
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashdot-ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - "dash"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashdot
            port:
              number: 3001
---
