apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  annotations:
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000
