apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  annotations:
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
    - protocol: TCP
      port: 53
      targetPort: 53
    - protocol: TCP
      port: 80
      targetPort: 80

