# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  labels:
    app: mealie
spec:
  selector:
    matchLabels:
      app: mealie
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  mealie
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 9000
          initialDelaySeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: mealie-config 
        ports:
        - containerPort: 9000
          name: mealie
        volumeMounts:
        - name: mealie-data
          mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc
      restartPolicy: Always
---

