# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mealie
spec:
  selector:
    app: mealie
  type: ClusterIP
  ports:
  - name: mealie
    protocol: TCP
    port: 9000
    targetPort: 9000
---

