
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homarr-ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - "homarr"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homarr
            port:
              number: 7575
---
