# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  labels:
    app: dashy
spec:
  selector:
    matchLabels:
      app: dashy
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  dashy
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name: dashy
        volumeMounts:
          - name: config-volume
            mountPath: /app/user-data/
      volumes:
        - name: config-volume
          configMap:
            name: dashy-config
      restartPolicy: Always
---

