# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: dashy
spec:
  selector:
    app: dashy
  type: ClusterIP
  ports:
  - name: dashy
    protocol: TCP
    port: 8080
    targetPort: 8080
---

