apiVersion: v2
name: nextcloud
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: nextclout
    repository: https://nextcloud.github.io/helm/
    version: 5.5.2
