apiVersion: v1
kind: ConfigMap
metadata:
  name: home-cm
data:
  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: disable
  services.yaml: |
    - Media
        - Jellyfin
            href: https://jellyfin.taila2ece.ts.net
            description: Media
            widget:
              type: jellyfin
              url: http://jellyfin.media:8096
              key: 13a3ddaed6b64a54afe9fc0d134be8c1
                enableBlocks: true
                enableNowPlaying: true
                enableUser: true 
                showEpisodeNumber: true
                expandOneStreamToTwoRows: false
  settings.yaml: |
    title: Homelab
    startUrl: https://home.taila2ece.ts.net
    theme: dark
    color: slate
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100
  widgets.yaml: |
    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
