---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media
  labels:
    app: overseerr
spec:
  selector:
    matchLabels:
      app: overseerr
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: overseerr
      labels:
        app: overseerr
    spec:
      containers:
      - name: overseerr
        image: fallenbagel/jellyseerr:latest
        envFrom:
        - configMapRef:
            name: overseerr-cm
        ports:
        - containerPort: 5055
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 5055
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          httpGet:
            port: 5055
          timeoutSeconds: 2
        volumeMounts:
        - name: data
          mountPath: /app/config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: overseerr-data
      restartPolicy: Always

