apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oversarr-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - "oversarr"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oversarr
            port:
              number: 5055
