# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
spec:
  selector:
    app: overseerr
  type: ClusterIP
  ports:
  - name: overseerr
    protocol: TCP
    port: 5055
    targetPort: 5055
---

